version: "3"
services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/etc/my.cnf:/etc/mysql/my.cnf:ro"
      - "./mysql/data:/var/lib/mysql"
      - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      TZ: 'Asia/Hong_Kong'
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"